name: Deploy DEV

on:
  pull_request:
    branches: [main]

jobs:
  deploy-env:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - name: NPM - Load cached venv
        id: cached-npm-dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: NPM - Install dependencies
        if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
        run: "npm install"

      - name: Deploy using sls
        run: "npx sls deploy"
        env:
            BUCKET: ${{secrets.BUCKET}}
            USER_NAME: ${{secrets.USER_NAME}}
            PASSWORD: ${{secrets.PASSWORD}}
            DATABASE: ${{secrets.DATABASE}}
            HOST: ${{secrets.HOST}}
            DATABASE_PORT: ${{secrets.DATABASE_PORT}}
            DIALECT: ${{secrets.DIALECT}}
            LOGGING: ${{secrets.LOGGING}}
            SSL: ${{secrets.SSL}}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Your SLS App was deployed!
            Awesome :D

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
